import type { ItemPublic } from "../types";

function item(p: ItemPublic): ItemPublic {
  return p;
}

const rights = "Original Anannt Education item. Not a College Board released question.";

export const ITEMS_4: ItemPublic[] = [
item({
    id: "u6-ad-e1",
    familyId: "fam-bc-optional",
    skillId: "sk-u6-antiderivative",
    lessonId: "u6-antiderivatives",
    stem: "Integration by parts is",
    type: "mcq",
    choices: [
      { id: "a", text: "required AB mastery content" },
      { id: "b", text: "BC-optional; excluded from AB mastery on this course" },
      { id: "c", text: "the same as substitution" },
      { id: "d", text: "needed for every exponential integral" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),

  // —— Units 7–8
  item({
    id: "u7-sf-c1",
    familyId: "fam-u7-verify",
    skillId: "sk-u7-verify",
    lessonId: "u7-slope-fields",
    stem: "Does $y=3e^{2x}$ solve $y'=2y$ with $y(0)=3$?",
    type: "mcq",
    choices: [
      { id: "a", text: "Yes: $y'=6e^{2x}=2y$ and $y(0)=3$." },
      { id: "b", text: "The DE holds but the initial condition fails." },
      { id: "c", text: "The initial condition holds but $y'\\neq 2y$." },
      { id: "d", text: "No, because Euler's method is required." },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u7-sf-i1",
    familyId: "fam-u7-slope",
    skillId: "sk-u7-slope",
    lessonId: "u7-slope-fields",
    stem: "In the slope field for $dy/dx=x$, the tick at $(2,5)$ has slope",
    type: "numeric",
    calculator: "none",
    representation: "graph",
    difficulty: 1,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u7-sf-e1",
    familyId: "fam-bc-euler",
    skillId: "sk-u7-slope",
    lessonId: "u7-slope-fields",
    stem: "Euler's method is",
    type: "mcq",
    choices: [
      { id: "a", text: "required for AB mastery" },
      { id: "b", text: "BC-optional and excluded from AB mastery here" },
      { id: "c", text: "the definition of a slope field" },
      { id: "d", text: "used to prove IVT" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u7-sp-c1",
    familyId: "fam-u7-sep",
    skillId: "sk-u7-separate",
    lessonId: "u7-separation",
    stem: "The particular solution of $y'=3y$, $y(0)=2$, $y>0$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "$y=2e^{3x}$" },
      { id: "b", text: "$y=e^{3x}+2$" },
      { id: "c", text: "$y=3e^{2x}$" },
      { id: "d", text: "$y=2x+2$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u7-sp-i1",
    familyId: "fam-u7-sep-num",
    skillId: "sk-u7-separate",
    lessonId: "u7-separation",
    stem: "If $y=2e^{3x}$, then $y(0)=$",
    type: "numeric",
    calculator: "none",
    representation: "numeric",
    difficulty: 1,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u7-sp-e1",
    familyId: "fam-bc-logistic",
    skillId: "sk-u7-separate",
    lessonId: "u7-separation",
    stem: "Logistic models are",
    type: "mcq",
    choices: [
      { id: "a", text: "required AB content" },
      { id: "b", text: "BC-optional; hidden from default AB mastery" },
      { id: "c", text: "identical to $y'=ky$" },
      { id: "d", text: "the only separable equations" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u8-an-c1",
    familyId: "fam-u8-net",
    skillId: "sk-u8-average",
    lessonId: "u8-avg-net",
    stem: "Velocity $v(t)=t-2$ on $[0,3]$. Net displacement equals",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u8",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u8-an-i1",
    familyId: "fam-u8-distance",
    skillId: "sk-u8-average",
    lessonId: "u8-avg-net",
    stem: "For the same $v$, total distance travelled on $[0,3]$ is",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u8",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u8-an-e1",
    familyId: "fam-u8-avg",
    skillId: "sk-u8-average",
    lessonId: "u8-avg-net",
    stem: "Average value of $f$ on $[a,b]$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "$\\int_a^b f$" },
      { id: "b", text: "$\\dfrac{1}{b-a}\\int_a^b f$" },
      { id: "c", text: "$f(b)-f(a)$" },
      { id: "d", text: "$f'(b)-f'(a)$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "u8",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u8-vo-c1",
    familyId: "fam-u8-disk",
    skillId: "sk-u8-volume",
    lessonId: "u8-volume",
    stem: "Region under $y=\\sqrt{x}$ from $0$ to $4$, rotated about the $x$-axis. The integrand of $\\pi\\int R^2\\,dx$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "$x$" },
      { id: "b", text: "$\\sqrt{x}$" },
      { id: "c", text: "$x^2$" },
      { id: "d", text: "$4$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u8",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u8-vo-i1",
    familyId: "fam-u8-volume-num",
    skillId: "sk-u8-volume",
    lessonId: "u8-volume",
    stem: "The volume in the previous setup is $k\\pi$. What is $k$?",
    type: "numeric",
    calculator: "none",
    representation: "numeric",
    difficulty: 2,
    unitId: "u8",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u8-vo-e1",
    familyId: "fam-bc-arc",
    skillId: "sk-u8-volume",
    lessonId: "u8-volume",
    stem: "Arc length integrals are",
    type: "mcq",
    choices: [
      { id: "a", text: "required AB mastery" },
      { id: "b", text: "BC-optional; excluded from AB mastery here" },
      { id: "c", text: "the same as disk volume" },
      { id: "d", text: "needed for average value" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u8",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),

  // —— Transfer / mixed review
  item({
    id: "tr-01",
    familyId: "fam-transfer-limit-ftc",
    skillId: "sk-u6-ftc",
    stem: "A graph of $f$ is unused here. If $A(x)=\\int_3^x f$ and $f$ is continuous, $A'(3)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$0$ always" },
      { id: "b", text: "$f(3)$" },
      { id: "c", text: "$f(x)$" },
      { id: "d", text: "$3$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "transfer",
  }),
  item({
    id: "tr-02",
    familyId: "fam-transfer-limit-graph",
    skillId: "sk-u1-limit-value",
    stem: "A jump: left-hand limit $2$, right-hand limit $5$, $f(1)=2$. Then $\\lim_{x\\to 1}f(x)$",
    type: "mcq",
    choices: [
      { id: "a", text: "equals $2$" },
      { id: "b", text: "equals $5$" },
      { id: "c", text: "does not exist" },
      { id: "d", text: "equals $3.5$" },
    ],
    calculator: "none",
    representation: "graph",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "transfer",
  }),

  // —— Mock short drill (original)
  item({
    id: "mock-ia-1",
    familyId: "fam-mock-limit",
    skillId: "sk-u1-limit-value",
    stem: "$\\lim_{x\\to 0}\\dfrac{(x+2)^2-4}{x}=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$0$" },
      { id: "b", text: "$2$" },
      { id: "c", text: "$4$" },
      { id: "d", text: "does not exist" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u1",
    protectedMock: true,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "mock-drill",
  }),
  item({
    id: "mock-ia-2",
    familyId: "fam-mock-deriv",
    skillId: "sk-u2-rules",
    stem: "If $f(x)=x^3-3x$, then $f'(1)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$0$" },
      { id: "b", text: "$3$" },
      { id: "c", text: "$-2$" },
      { id: "d", text: "$6$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u2",
    protectedMock: true,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "mock-drill",
  }),
  item({
    id: "mock-ia-3",
    familyId: "fam-mock-chain",
    skillId: "sk-u3-chain",
    stem: "$\\dfrac{d}{dx}e^{5x}=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$e^{5x}$" },
      { id: "b", text: "$5e^{5x}$" },
      { id: "c", text: "$5x e^{5x}$" },
      { id: "d", text: "$e^{x^5}$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u3",
    protectedMock: true,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "mock-drill",
  }),
  item({
    id: "mock-ia-4",
    familyId: "fam-mock-ftc",
    skillId: "sk-u6-ftc",
    stem: "$\\dfrac{d}{dx}\\int_1^x \\cos t\\,dt=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$\\cos x$" },
      { id: "b", text: "$\\sin x-\\sin 1$" },
      { id: "c", text: "$-\\sin x$" },
      { id: "d", text: "$\\cos x-\\cos 1$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u6",
    protectedMock: true,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "mock-drill",
  }),
  item({
    id: "mock-ib-1",
    familyId: "fam-mock-calc-num",
    skillId: "sk-u5-extrema",
    stem: "A calculator-required item: $f(x)=x^3-3x+1$ on $[-2,2]$. Which is closest to the absolute minimum value?",
    type: "mcq",
    choices: [
      { id: "a", text: "$-3$" },
      { id: "b", text: "$-1$" },
      { id: "c", text: "$1$" },
      { id: "d", text: "$-2$" },
    ],
    calculator: "required",
    representation: "numeric",
    difficulty: 3,
    unitId: "u5",
    protectedMock: true,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "mock-drill",
  }),
  item({
    id: "mock-ib-2",
    familyId: "fam-mock-calc-int",
    skillId: "sk-u8-average",
    stem: "Calculator required. Average value of $f(x)=e^{-x^2}$ on $[0,1]$ is closest to",
    type: "mcq",
    choices: [
      { id: "a", text: "$0.75$" },
      { id: "b", text: "$0.25$" },
      { id: "c", text: "$1.00$" },
      { id: "d", text: "$0.10$" },
    ],
    calculator: "required",
    representation: "numeric",
    difficulty: 4,
    unitId: "u8",
    protectedMock: true,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "mock-drill",
  })
];
