import type { ItemPublic } from "../types";

function item(p: ItemPublic): ItemPublic {
  return p;
}

const rights = "Original Anannt Education item. Not a College Board released question.";

export const ITEMS_2: ItemPublic[] = [
item({
    id: "u1-lv-c1",
    familyId: "fam-u1-limit-value",
    skillId: "sk-u1-limit-value",
    lessonId: "u1-limit-vs-value",
    stem: "Let $f(x)=\\dfrac{x^2-1}{x-1}$ for $x\\neq 1$ and $f(1)=4$. Then $\\lim_{x\\to 1}f(x)=$",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u1-lv-c2",
    familyId: "fam-u1-limit-value",
    skillId: "sk-u1-limit-value",
    lessonId: "u1-limit-vs-value",
    stem: "For the same $f$ as the previous item, $f(1)=$",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u1-lv-c3",
    familyId: "fam-u1-filled-point",
    skillId: "sk-u1-limit-value",
    lessonId: "u1-limit-vs-value",
    stem: "You move only the filled point at $x=1$ on a graph whose nearby curve is unchanged. Which quantity can change?",
    type: "mcq",
    choices: [
      { id: "a", text: "The two-sided limit as $x\\to 1$" },
      { id: "b", text: "The hole height of the nearby curve" },
      { id: "c", text: "The declared value $f(1)$" },
      { id: "d", text: "Both the limit and $f(1)$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u1-lv-i1",
    familyId: "fam-u1-table",
    skillId: "sk-u1-limit-value",
    lessonId: "u1-limit-vs-value",
    stem: "A table for $g$ lists: $x=1.9,\\ 1.99,\\ 2.01,\\ 2.1$ with $g(x)=3.9,\\ 3.99,\\ 4.01,\\ 4.1$, while $g(2)$ is undefined. The best estimate of $\\lim_{x\\to 2}g(x)$ is",
    type: "numeric",
    calculator: "none",
    representation: "table",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u1-lv-i2",
    familyId: "fam-u1-piecewise",
    skillId: "sk-u1-onesided",
    lessonId: "u1-limit-vs-value",
    stem: "Let $p(x)=\\begin{cases} x+1 & x<0 \\\\ 4 & x=0 \\\\ x+1 & x>0 \\end{cases}$. Then $\\lim_{x\\to 0}p(x)$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "$4$" },
      { id: "b", text: "$1$" },
      { id: "c", text: "$0$" },
      { id: "d", text: "does not exist" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u1-lv-e1",
    familyId: "fam-u1-explain",
    skillId: "sk-u1-limit-value",
    lessonId: "u1-limit-vs-value",
    stem: "Explain in one sentence why a limit can exist even if $f(a)$ is undefined. (Choose the best statement.)",
    type: "mcq",
    choices: [
      { id: "a", text: "Because limits only use nearby $x$-values, not the value at $a$." },
      { id: "b", text: "Because every hole can be ignored in every theorem." },
      { id: "c", text: "Because $f(a)$ is always equal to the average of nearby values." },
      { id: "d", text: "Because undefined points make the limit infinite." },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u1-co-c1",
    familyId: "fam-u1-continuity",
    skillId: "sk-u1-continuity",
    lessonId: "u1-continuity",
    stem: "For continuity of $f$ at $a$, which list is complete?",
    type: "mcq",
    choices: [
      { id: "a", text: "$f(a)$ exists" },
      { id: "b", text: "the limit exists" },
      { id: "c", text: "$f(a)$ exists, the limit exists, and they are equal" },
      { id: "d", text: "$f$ is a polynomial" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u1-co-c2",
    familyId: "fam-u1-ivt",
    skillId: "sk-u1-ivt",
    lessonId: "u1-continuity",
    stem: "Why can we not apply IVT to $\\tan x$ on $[\\pi/4, 3\\pi/4]$ even though the endpoint values have opposite signs?",
    type: "mcq",
    choices: [
      { id: "a", text: "$\\tan x$ is not continuous on that closed interval" },
      { id: "b", text: "IVT never applies to trigonometric functions" },
      { id: "c", text: "The interval is too short" },
      { id: "d", text: "The endpoints are not integers" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u1-co-i1",
    familyId: "fam-u1-ivt-apply",
    skillId: "sk-u1-ivt",
    lessonId: "u1-continuity",
    stem: "$q(x)=x^3-x-1$ is a polynomial. $q(1)=-1$ and $q(2)=5$. What does IVT guarantee?",
    type: "mcq",
    choices: [
      { id: "a", text: "A root in $(1,2)$" },
      { id: "b", text: "A root at $x=1.5$" },
      { id: "c", text: "Two roots in $(1,2)$" },
      { id: "d", text: "Nothing, because we did not factor $q$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u1-co-e1",
    familyId: "fam-u1-continuity",
    skillId: "sk-u1-continuity",
    lessonId: "u1-continuity",
    stem: "If $\\lim_{x\\to a}f(x)=f(a)$, then $f$ is continuous at $a$, provided also that",
    type: "mcq",
    choices: [
      { id: "a", text: "the limit exists — which is already implied — and $f(a)$ is defined, also implied. The statement is already the definition." },
      { id: "b", text: "$f$ is differentiable" },
      { id: "c", text: "$f$ is a polynomial" },
      { id: "d", text: "$a=0$" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),

  // —— Units 2–5 compact items
  item({
    id: "u2-df-c1",
    familyId: "fam-u2-definition",
    skillId: "sk-u2-definition",
    lessonId: "u2-derivative-limit",
    stem: "The derivative $f'(a)$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "the slope of one particular secant through $(a,f(a))$" },
      { id: "b", text: "the limit of secant slopes $\\frac{f(a+h)-f(a)}{h}$ as $h\\to 0$, if it exists" },
      { id: "c", text: "always equal to $f(a)$" },
      { id: "d", text: "undefined if $f(a)=0$" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u2-df-i1",
    familyId: "fam-u2-corner",
    skillId: "sk-u2-differentiability",
    lessonId: "u2-derivative-limit",
    stem: "The graph of $y=|x|$ at $x=0$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "differentiable and continuous" },
      { id: "b", text: "continuous but not differentiable" },
      { id: "c", text: "differentiable but not continuous" },
      { id: "d", text: "neither continuous nor defined" },
    ],
    calculator: "none",
    representation: "graph",
    difficulty: 2,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u2-df-e1",
    familyId: "fam-u2-units",
    skillId: "sk-u2-definition",
    lessonId: "u2-derivative-limit",
    stem: "If $f$ is litres and $t$ is minutes, $f'(t)$ has units",
    type: "mcq",
    choices: [
      { id: "a", text: "litres" },
      { id: "b", text: "minutes" },
      { id: "c", text: "litres per minute" },
      { id: "d", text: "minutes per litre" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u2-ru-c1",
    familyId: "fam-u2-product",
    skillId: "sk-u2-rules",
    lessonId: "u2-elementary-rules",
    stem: "The product rule for $(fg)'$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "$f'g'$" },
      { id: "b", text: "$f'g+fg'$" },
      { id: "c", text: "$f'+g'$" },
      { id: "d", text: "$f'g-fg'$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u2-ru-i1",
    familyId: "fam-u2-quotient",
    skillId: "sk-u2-rules",
    lessonId: "u2-elementary-rules",
    stem: "If $y=\\dfrac{x}{x+1}$, then $y'(1)=$",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u2-ru-e1",
    familyId: "fam-u2-product",
    skillId: "sk-u2-rules",
    lessonId: "u2-elementary-rules",
    stem: "$(x^2 e^x)'$ at $x=0$ equals",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u3-ch-c1",
    familyId: "fam-u3-chain",
    skillId: "sk-u3-chain",
    lessonId: "u3-chain",
    stem: "$\\dfrac{d}{dx}\\cos(3x)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$-\\sin(3x)$" },
      { id: "b", text: "$-3\\sin(3x)$" },
      { id: "c", text: "$3\\sin(3x)$" },
      { id: "d", text: "$-3\\cos(3x)$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u3-ch-i1",
    familyId: "fam-u3-chain-nested",
    skillId: "sk-u3-chain",
    lessonId: "u3-chain",
    stem: "If $y=(2x+1)^4$, then $y'(0)=$",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u3-ch-e1",
    familyId: "fam-u3-chain",
    skillId: "sk-u3-chain",
    lessonId: "u3-chain",
    stem: "The extra factor in the chain rule exists because",
    type: "mcq",
    choices: [
      { id: "a", text: "the inner function is itself changing with $x$" },
      { id: "b", text: "sine is an odd function" },
      { id: "c", text: "constants always differentiate to themselves" },
      { id: "d", text: "the outer function is linear" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u3-im-c1",
    familyId: "fam-u3-implicit",
    skillId: "sk-u3-implicit",
    lessonId: "u3-implicit",
    stem: "If $x^2+y^2=25$, then $dy/dx=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$-x/y$" },
      { id: "b", text: "$x/y$" },
      { id: "c", text: "$-y/x$" },
      { id: "d", text: "$2x+2y$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u3-im-i1",
    familyId: "fam-u3-inverse",
    skillId: "sk-u3-inverse",
    lessonId: "u3-implicit",
    stem: "If $f(2)=5$ and $f'(2)=4$, then $(f^{-1})'(5)=$",
    type: "numeric",
    calculator: "none",
    representation: "numeric",
    difficulty: 3,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  })
];
