import type { ItemPublic } from "../types";

function item(p: ItemPublic): ItemPublic {
  return p;
}

const rights = "Original Anannt Education item. Not a College Board released question.";

export const ITEMS_A: ItemPublic[] = [
  // —— Diagnostic (allow not learned)
  item({
    id: "diag-01",
    familyId: "fam-f-notation",
    skillId: "sk-f-notation",
    stem: "If $f(x)=3x-1$ and $g(x)=x^2$, what is $f(g(2))$?",
    type: "mcq",
    choices: [
      { id: "a", text: "$11$" },
      { id: "b", text: "$25$" },
      { id: "c", text: "$5$" },
      { id: "d", text: "$35$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "foundation",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-02",
    familyId: "fam-f-domain",
    skillId: "sk-f-domain",
    stem: "Which $x$-values are excluded from the domain of $h(x)=\\dfrac{x-1}{x^2-1}$?",
    type: "mcq",
    choices: [
      { id: "a", text: "only $x=1$" },
      { id: "b", text: "only $x=-1$" },
      { id: "c", text: "$x=1$ and $x=-1$" },
      { id: "d", text: "none; the $x-1$ cancels" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "foundation",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-03",
    familyId: "fam-f-trig",
    skillId: "sk-f-trig",
    stem: "What is $\\cos(\\pi)$?",
    type: "mcq",
    choices: [
      { id: "a", text: "$1$" },
      { id: "b", text: "$0$" },
      { id: "c", text: "$-1$" },
      { id: "d", text: "$\\pi$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "foundation",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-04",
    familyId: "fam-f-slope",
    skillId: "sk-f-slope",
    stem: "A tank has volume $V$ litres after $t$ minutes. If $V$ is linear with slope $-4$, what does $-4$ mean?",
    type: "mcq",
    choices: [
      { id: "a", text: "The tank contains $4$ litres." },
      { id: "b", text: "The tank loses $4$ litres each minute." },
      { id: "c", text: "The tank will be empty in $4$ minutes." },
      { id: "d", text: "The height of the graph is $4$." },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "foundation",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-05",
    familyId: "fam-u1-limit-value",
    skillId: "sk-u1-limit-value",
    stem: "A graph of $y=f(x)$ has a hole at $(2,3)$ and a filled point at $(2,5)$. What is $\\lim_{x\\to 2}f(x)$ if the nearby curve approaches height $3$?",
    type: "mcq",
    choices: [
      { id: "a", text: "$5$, because that is the filled point" },
      { id: "b", text: "$3$" },
      { id: "c", text: "does not exist, because $f(2)\\neq 3$" },
      { id: "d", text: "$2$" },
    ],
    calculator: "none",
    representation: "graph",
    difficulty: 2,
    unitId: "u1",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-06",
    familyId: "fam-u2-definition",
    skillId: "sk-u2-definition",
    stem: "$s(t)$ is position in metres after $t$ seconds. What are the units of $s'(t)$?",
    type: "mcq",
    choices: [
      { id: "a", text: "metres" },
      { id: "b", text: "seconds" },
      { id: "c", text: "metres per second" },
      { id: "d", text: "metres per second squared" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-07",
    familyId: "fam-u2-rules",
    skillId: "sk-u2-rules",
    stem: "If $f(x)=x^3$, then $f'(x)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$3x^2$" },
      { id: "b", text: "$x^2$" },
      { id: "c", text: "$3x$" },
      { id: "d", text: "$x^4/4$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "u2",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-08",
    familyId: "fam-u3-chain",
    skillId: "sk-u3-chain",
    stem: "$\\dfrac{d}{dx}\\sin(2x)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$\\cos(2x)$" },
      { id: "b", text: "$2\\cos(2x)$" },
      { id: "c", text: "$-\\cos(2x)$" },
      { id: "d", text: "$2\\sin(2x)$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-09",
    familyId: "fam-u6-accumulation",
    skillId: "sk-u6-accumulation",
    stem: "If $f$ is negative on $[1,4]$, then $\\int_1^4 f(x)\\,dx$ is",
    type: "mcq",
    choices: [
      { id: "a", text: "positive, because area is positive" },
      { id: "b", text: "negative" },
      { id: "c", text: "zero" },
      { id: "d", text: "undefined, because $f$ is negative" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-10",
    familyId: "fam-u6-ftc",
    skillId: "sk-u6-ftc",
    stem: "If $A(x)=\\int_2^x f(t)\\,dt$ and $f$ is continuous, then $A'(x)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$f(x)$" },
      { id: "b", text: "$f(2)$" },
      { id: "c", text: "$f(x)-f(2)$" },
      { id: "d", text: "$\\int_2^x f'(t)\\,dt$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-11",
    familyId: "fam-u5-extrema",
    skillId: "sk-u5-extrema",
    stem: "If $f'(c)=0$, which conclusion is always justified?",
    type: "mcq",
    choices: [
      { id: "a", text: "$f$ has a local maximum at $c$." },
      { id: "b", text: "$f$ has a local minimum at $c$." },
      { id: "c", text: "$c$ is a critical point of $f$ (assuming $c$ is in the domain)." },
      { id: "d", text: "$f$ is not continuous at $c$." },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
  item({
    id: "diag-12",
    familyId: "fam-u7-verify",
    skillId: "sk-u7-verify",
    stem: "Does $y=e^{3x}$ satisfy $y'=3y$?",
    type: "mcq",
    choices: [
      { id: "a", text: "Yes, because $y'=3e^{3x}=3y$." },
      { id: "b", text: "No, because the exponent should be $-3x$." },
      { id: "c", text: "Yes, but only if $y(0)=0$." },
      { id: "d", text: "No, because $y'=e^{3x}$." },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u7",
    protectedMock: false,
    allowNotLearned: true,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "diagnostic",
  }),
];
