import type { ItemPublic } from "../types";

function item(p: ItemPublic): ItemPublic {
  return p;
}

const rights = "Original Anannt Education item. Not a College Board released question.";

export const ITEMS_3: ItemPublic[] = [
item({
    id: "u3-im-e1",
    familyId: "fam-u3-implicit",
    skillId: "sk-u3-implicit",
    lessonId: "u3-implicit",
    stem: "When differentiating $y^3$ with respect to $x$, the chain rule produces",
    type: "mcq",
    choices: [
      { id: "a", text: "$3y^2$" },
      { id: "b", text: "$3y^2 y'$" },
      { id: "c", text: "$3y^3$" },
      { id: "d", text: "$y'$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u3",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u4-cx-c1",
    familyId: "fam-u4-context",
    skillId: "sk-u4-context",
    lessonId: "u4-context",
    stem: "$H(4)=30$ cm and $H'(4)=-2$ cm/min. At $t=4$ minutes, the water height is",
    type: "mcq",
    choices: [
      { id: "a", text: "rising at $2$ cm/min" },
      { id: "b", text: "falling at $2$ cm/min" },
      { id: "c", text: "$2$ cm deep" },
      { id: "d", text: "constant" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u4",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u4-cx-i1",
    familyId: "fam-u4-linear",
    skillId: "sk-u4-linear",
    lessonId: "u4-context",
    stem: "Using the tangent at $t=4$, estimate $H(4.5)$ if $H(4)=30$ and $H'(4)=-2$.",
    type: "numeric",
    calculator: "none",
    representation: "numeric",
    difficulty: 2,
    unitId: "u4",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u4-cx-e1",
    familyId: "fam-u4-context",
    skillId: "sk-u4-context",
    lessonId: "u4-context",
    stem: "A local linear estimate is most reliable when",
    type: "mcq",
    choices: [
      { id: "a", text: "the step $\\Delta t$ is small" },
      { id: "b", text: "the function is a cubic" },
      { id: "c", text: "we are far from the known point" },
      { id: "d", text: "the derivative is zero everywhere else" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u4",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u4-rr-c1",
    familyId: "fam-u4-related",
    skillId: "sk-u4-related",
    lessonId: "u4-related-rates",
    stem: "Oil slick: $A=\\pi r^2$. The correct first differentiation is",
    type: "mcq",
    choices: [
      { id: "a", text: "$\\frac{dA}{dt}=2\\pi r\\frac{dr}{dt}$" },
      { id: "b", text: "$\\frac{dA}{dt}=2\\pi r$" },
      { id: "c", text: "$A=\\pi(5)^2$ then $dA/dt=0$" },
      { id: "d", text: "$\\frac{dA}{dt}=\\pi r^2 \\frac{dr}{dt}$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u4",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u4-rr-i1",
    familyId: "fam-u4-related-num",
    skillId: "sk-u4-related",
    lessonId: "u4-related-rates",
    stem: "If $r=5$ m and $dr/dt=0.2$ m/s, then $dA/dt$ in m$^2$/s equals $2\\pi$ times what number? Enter that number (the coefficient of $\\pi$ is not needed; enter $dA/dt$ divided by $\\pi$).",
    type: "numeric",
    calculator: "none",
    representation: "numeric",
    difficulty: 3,
    unitId: "u4",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u4-rr-e1",
    familyId: "fam-u4-related",
    skillId: "sk-u4-related",
    lessonId: "u4-related-rates",
    stem: "Substituting $r=5$ before differentiating $A=\\pi r^2$ wrongly suggests",
    type: "mcq",
    choices: [
      { id: "a", text: "$dA/dt=0$ because $A$ looks constant" },
      { id: "b", text: "a larger rate" },
      { id: "c", text: "the radius is decreasing" },
      { id: "d", text: "the units become seconds" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u4",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u5-ex-c1",
    familyId: "fam-u5-extrema",
    skillId: "sk-u5-extrema",
    lessonId: "u5-extrema",
    stem: "For $f(x)=x^3$, $f'(0)=0$. This critical point is",
    type: "mcq",
    choices: [
      { id: "a", text: "a local maximum" },
      { id: "b", text: "a local minimum" },
      { id: "c", text: "not a local extremum" },
      { id: "d", text: "an absolute minimum on $\\mathbb{R}$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u5-ex-i1",
    familyId: "fam-u5-closed",
    skillId: "sk-u5-optimisation",
    lessonId: "u5-extrema",
    stem: "Absolute maximum of $f(x)=x^3$ on $[-1,2]$ is",
    type: "numeric",
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u5-ex-e1",
    familyId: "fam-u5-mvt",
    skillId: "sk-u5-theorems",
    lessonId: "u5-extrema",
    stem: "MVT on $[a,b]$ requires, among other things,",
    type: "mcq",
    choices: [
      { id: "a", text: "differentiability on $(a,b)$ and continuity on $[a,b]$" },
      { id: "b", text: "only $f(a)=f(b)$" },
      { id: "c", text: "that $f$ is a polynomial of even degree" },
      { id: "d", text: "that $f'$ never zero" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u5-fp-c1",
    familyId: "fam-u5-from-fp",
    skillId: "sk-u5-extrema",
    lessonId: "u5-from-derivative",
    stem: "If $f'$ changes from positive to negative at $c$, then $f$ has",
    type: "mcq",
    choices: [
      { id: "a", text: "a local minimum at $c$" },
      { id: "b", text: "a local maximum at $c$" },
      { id: "c", text: "an inflection point only, never an extremum" },
      { id: "d", text: "$f(c)=0$" },
    ],
    calculator: "none",
    representation: "graph",
    difficulty: 2,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u5-fp-i1",
    familyId: "fam-u5-from-fp-height",
    skillId: "sk-u5-extrema",
    lessonId: "u5-from-derivative",
    stem: "A graph of $f'$ does not by itself determine",
    type: "mcq",
    choices: [
      { id: "a", text: "where $f$ increases" },
      { id: "b", text: "the exact vertical placement of $f$ (without a point on $f$)" },
      { id: "c", text: "where $f$ has a horizontal tangent" },
      { id: "d", text: "the concavity of $f$ if $f'$ is itself increasing or decreasing" },
    ],
    calculator: "none",
    representation: "graph",
    difficulty: 3,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u5-fp-e1",
    familyId: "fam-u5-from-fp",
    skillId: "sk-u5-extrema",
    lessonId: "u5-from-derivative",
    stem: "Heights on the graph of $f'$ correspond to",
    type: "mcq",
    choices: [
      { id: "a", text: "heights of $f$" },
      { id: "b", text: "slopes of $f$" },
      { id: "c", text: "areas under $f$" },
      { id: "d", text: "zeros of $f$ only" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 1,
    unitId: "u5",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),

  // —— Unit 6 FTC deep items
  item({
    id: "u6-ftc-c1",
    familyId: "fam-u6-sign",
    skillId: "sk-u6-accumulation",
    lessonId: "u6-ftc",
    stem: "Let $f(t)=t-2$ and $A(x)=\\int_0^x f(t)\\,dt$. On the interval $0<x<2$, $A$ is",
    type: "predict",
    choices: [
      { id: "a", text: "increasing, because there is area between the graph and the axis" },
      { id: "b", text: "decreasing, because $f$ is negative so signed accumulation is falling" },
      { id: "c", text: "constant, because $A(0)=0$" },
      { id: "d", text: "undefined, because $f$ changes later at $t=2$" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u6-ftc-c2",
    familyId: "fam-u6-ftc",
    skillId: "sk-u6-ftc",
    lessonId: "u6-ftc",
    stem: "With the same $A$ and $f$, $A'(x)=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$x-2$" },
      { id: "b", text: "$x^2/2-2x$" },
      { id: "c", text: "$2$" },
      { id: "d", text: "$0$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u6-ftc-c3",
    familyId: "fam-u6-chain-ftc",
    skillId: "sk-u6-ftc",
    lessonId: "u6-ftc",
    stem: "$\\dfrac{d}{dx}\\displaystyle\\int_0^{x^2}(t-2)\\,dt=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$x^2-2$  (sign of $f$ at the upper limit, but missing the chain factor)" },
      { id: "b", text: "$(x^2-2)\\cdot 2x$" },
      { id: "c", text: "$x-2$" },
      { id: "d", text: "$2x$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 3,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u6-ftc-i1",
    familyId: "fam-u6-table-ftc",
    skillId: "sk-u6-ftc",
    lessonId: "u6-ftc",
    stem: "Selected values of a continuous $f$: $x=0,1,2,4$ with $f(x)=3,1,-2,0$. If $B(x)=\\int_1^{x} f$, then $B'(2)=$",
    type: "numeric",
    calculator: "none",
    representation: "table",
    difficulty: 3,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u6-ftc-i2",
    familyId: "fam-u6-graph-chain",
    skillId: "sk-u6-ftc",
    lessonId: "u6-ftc",
    stem: "The graph of continuous $f$ has $f(4)=-1$. If $C(x)=\\int_0^{x^2} f(t)\\,dt$, then $C'(2)=$",
    type: "numeric",
    calculator: "none",
    representation: "graph",
    difficulty: 4,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  }),
  item({
    id: "u6-ftc-e1",
    familyId: "fam-u6-signed-area",
    skillId: "sk-u6-accumulation",
    lessonId: "u6-ftc",
    stem: "Geometric area between $y=f$ and the $x$-axis on $[a,b]$ equals $\\int_a^b f$ when",
    type: "mcq",
    choices: [
      { id: "a", text: "always" },
      { id: "b", text: "only when $f\\ge 0$ on $[a,b]$ (otherwise split and use absolute values)" },
      { id: "c", text: "only when $f$ is a polynomial" },
      { id: "d", text: "never; they are unrelated" },
    ],
    calculator: "none",
    representation: "verbal",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u6-ad-c1",
    familyId: "fam-u6-sub",
    skillId: "sk-u6-antiderivative",
    lessonId: "u6-antiderivatives",
    stem: "$\\int 2x\\cos(x^2)\\,dx=$",
    type: "mcq",
    choices: [
      { id: "a", text: "$\\sin(x^2)+C$" },
      { id: "b", text: "$\\cos(x^2)+C$" },
      { id: "c", text: "$2\\sin(x^2)+C$" },
      { id: "d", text: "$x^2\\cos(x^2)+C$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 2,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "lesson",
  }),
  item({
    id: "u6-ad-i1",
    familyId: "fam-u6-anti",
    skillId: "sk-u6-antiderivative",
    lessonId: "u6-antiderivatives",
    stem: "An antiderivative of $3x^2$ is $x^3$. Another is",
    type: "mcq",
    choices: [
      { id: "a", text: "$x^3+5$" },
      { id: "b", text: "$3x^3$" },
      { id: "c", text: "$x^2$" },
      { id: "d", text: "$6x$" },
    ],
    calculator: "none",
    representation: "analytic",
    difficulty: 1,
    unitId: "u6",
    protectedMock: false,
    allowNotLearned: false,
    status: "published",
    authorId: "author-anannt-calc",
    reviewerId: "approver-anannt-academic",
    rights,
    pool: "independent",
  })
];
