import type { Skill, Unit } from "../types";
import { DEFAULT_EVIDENCE } from "../exam-config";

const P = DEFAULT_EVIDENCE;

export const UNITS: Unit[] = [
  {
    id: "foundation",
    number: "F",
    title: "Foundation bridge",
    officialLabel: "Anannt prerequisite modules (test-out possible)",
    mcqWeight: "not scored on AP MCQ",
    overview:
      "Short algebra and precalculus repair so a notation or factoring error does not become a whole calculus unit. Each module can be tested out. These skills are required for AB work but are not AP units.",
    signatureActivity: "Test out a module with a 5-minute check, or complete the short lesson if the diagnostic flagged it.",
    lessonIds: ["f-notation", "f-domain", "f-slope"],
    skillIds: ["sk-f-notation", "sk-f-domain", "sk-f-trig", "sk-f-slope"],
    isFoundation: true,
  },
  {
    id: "u1",
    number: 1,
    title: "Limits and Continuity",
    officialLabel: "Unit 1: Limits and Continuity",
    mcqWeight: "10–15%",
    overview:
      "A limit describes nearby behaviour, not a filled point. Continuity is a three-part checklist used before existence theorems. This unit trains you to say what a graph, table, or algebraically simplified expression is actually claiming.",
    signatureActivity:
      "Move a graph's filled point while nearby behaviour stays fixed, then predict what changes (limit versus function value).",
    lessonIds: ["u1-limit-vs-value", "u1-continuity"],
    skillIds: ["sk-u1-limit-value", "sk-u1-onesided", "sk-u1-continuity", "sk-u1-ivt"],
  },
  {
    id: "u2",
    number: 2,
    title: "Differentiation: Definition and Fundamental Properties",
    officialLabel: "Unit 2: Differentiation: Definition and Fundamental Properties",
    mcqWeight: "10–15%",
    overview:
      "The derivative is a limit of average rates. Units matter. A corner can have one-sided derivatives that disagree even when the graph has a turning appearance.",
    signatureActivity:
      "Move a secant point toward a fixed point and compare slope estimates with the tangent interpretation.",
    lessonIds: ["u2-derivative-limit", "u2-elementary-rules"],
    skillIds: ["sk-u2-definition", "sk-u2-differentiability", "sk-u2-rules"],
  },
  {
    id: "u3",
    number: 3,
    title: "Differentiation: Composite, Implicit, and Inverse Functions",
    officialLabel: "Unit 3: Differentiation: Composite, Implicit, and Inverse Functions",
    mcqWeight: "5–10%",
    overview:
      "Read structure first. Nested functions need named inner pieces before the chain rule. Implicit work treats y as a function of x without solving. Inverse derivatives use the reciprocal slope idea with a domain check.",
    signatureActivity: "Annotate nested functions before differentiating, then justify each chain factor.",
    lessonIds: ["u3-chain", "u3-implicit"],
    skillIds: ["sk-u3-chain", "sk-u3-implicit", "sk-u3-inverse"],
  },
  {
    id: "u4",
    number: 4,
    title: "Contextual Applications of Differentiation",
    officialLabel: "Unit 4: Contextual Applications of Differentiation",
    mcqWeight: "10–15%",
    overview:
      "A verbal rate is a signed quantity with units. Related rates start from a diagram and an equation, then substitution happens last. Local linear approximation is a tangent, not a promise of global accuracy.",
    signatureActivity:
      "Build a related-rates equation before substituting instantaneous measurements.",
    lessonIds: ["u4-context", "u4-related-rates"],
    skillIds: ["sk-u4-context", "sk-u4-related", "sk-u4-linear"],
  },
  {
    id: "u5",
    number: 5,
    title: "Analytical Applications of Differentiation",
    officialLabel: "Unit 5: Analytical Applications of Differentiation",
    mcqWeight: "15–20%",
    overview:
      "Theorems have hypotheses. Extrema arguments use sign changes on intervals, not a second-derivative slogan used out of range. Graph relationships ask you to reconstruct possible behaviour from $f'$.",
    signatureActivity: "Reconstruct possible function behaviour from a derivative graph.",
    lessonIds: ["u5-extrema", "u5-from-derivative"],
    skillIds: ["sk-u5-theorems", "sk-u5-extrema", "sk-u5-optimisation"],
  },
  {
    id: "u6",
    number: 6,
    title: "Integration and Accumulation of Change",
    officialLabel: "Unit 6: Integration and Accumulation of Change",
    mcqWeight: "15–20%",
    overview:
      "Accumulation is signed. Geometric area is a related but different request. The FTC connects $A(x)=\\int_a^x f$ to $A'(x)=f(x)$ when $f$ is continuous, and a variable upper limit needs the chain rule.",
    signatureActivity:
      "Predict whether $A$ rises when $f$ is negative before the running-accumulation graph is revealed.",
    lessonIds: ["u6-ftc", "u6-antiderivatives"],
    skillIds: ["sk-u6-accumulation", "sk-u6-ftc", "sk-u6-antiderivative"],
  },
  {
    id: "u7",
    number: 7,
    title: "Differential Equations",
    officialLabel: "Unit 7: Differential Equations",
    mcqWeight: "5–10%",
    overview:
      "A proposed solution is checked by differentiation and substitution. Slope fields show local linear behaviour. Separation with an initial condition produces a particular solution. Logistic models and Euler's method are BC and are excluded from AB mastery.",
    signatureActivity: "Select and justify a solution curve through a slope field.",
    lessonIds: ["u7-slope-fields", "u7-separation"],
    skillIds: ["sk-u7-verify", "sk-u7-slope", "sk-u7-separate"],
  },
  {
    id: "u8",
    number: 8,
    title: "Applications of Integration",
    officialLabel: "Unit 8: Applications of Integration",
    mcqWeight: "10–15%",
    overview:
      "Average value, net and total change, area, and volumes from slices. Draw the slice, name the radius or height, and keep units. Arc length, parametric, polar, and vector work are BC and stay optional labels only.",
    signatureActivity: "Draw a representative slice before constructing a volume integral.",
    lessonIds: ["u8-avg-net", "u8-volume"],
    skillIds: ["sk-u8-average", "sk-u8-area", "sk-u8-volume"],
  },
];

export const SKILLS: Skill[] = [
  {
    id: "sk-f-notation",
    title: "Function notation and composition",
    description: "Evaluate $f(g(x))$ and reverse the order; interpret $f(a+h)$.",
    unitId: "foundation",
    cedTopic: "Prerequisite",
    cedObjective: "FUN-pre",
    cedEK: "F.NOTATION",
    prerequisites: [],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "f-notation",
  },
  {
    id: "sk-f-domain",
    title: "Domain, range, and piecewise reading",
    description: "State domain restrictions and read a piecewise graph, including holes.",
    unitId: "foundation",
    cedTopic: "Prerequisite",
    cedObjective: "FUN-pre",
    cedEK: "F.DOMAIN",
    prerequisites: ["sk-f-notation"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "f-domain",
  },
  {
    id: "sk-f-trig",
    title: "Trigonometry in radians",
    description: "Evaluate sine and cosine at standard radian measures and use the unit circle.",
    unitId: "foundation",
    cedTopic: "Prerequisite",
    cedObjective: "FUN-pre",
    cedEK: "F.TRIG",
    prerequisites: [],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "f-domain",
  },
  {
    id: "sk-f-slope",
    title: "Slope, units, and linear change",
    description: "Interpret slope as a rate with units; write a linear model from two points.",
    unitId: "foundation",
    cedTopic: "Prerequisite",
    cedObjective: "FUN-pre",
    cedEK: "F.SLOPE",
    prerequisites: [],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "f-slope",
  },
  {
    id: "sk-u1-limit-value",
    title: "Limit versus function value",
    description: "Distinguish $\\lim_{x\\to a}f(x)$ from $f(a)$, including removable discontinuities.",
    unitId: "u1",
    cedTopic: "1.2–1.3",
    cedObjective: "LIM-1.A",
    cedEK: "LIM-1.A.1",
    prerequisites: ["sk-f-notation", "sk-f-domain"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u1-limit-vs-value",
  },
  {
    id: "sk-u1-onesided",
    title: "One-sided limits and algebraic methods",
    description: "Estimate one-sided limits from graphs and tables; simplify algebraically when valid.",
    unitId: "u1",
    cedTopic: "1.3–1.6",
    cedObjective: "LIM-1.B",
    cedEK: "LIM-1.C.1",
    prerequisites: ["sk-u1-limit-value"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u1-limit-vs-value",
  },
  {
    id: "sk-u1-continuity",
    title: "Continuity checklist",
    description: "Check $f(a)$ exists, the limit exists, and the two agree, before using existence theorems.",
    unitId: "u1",
    cedTopic: "1.10–1.11",
    cedObjective: "LIM-2.A",
    cedEK: "LIM-2.A.1",
    prerequisites: ["sk-u1-limit-value", "sk-u1-onesided"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u1-continuity",
  },
  {
    id: "sk-u1-ivt",
    title: "Intermediate Value Theorem conditions",
    description: "State IVT hypotheses and what the theorem does and does not guarantee.",
    unitId: "u1",
    cedTopic: "1.16",
    cedObjective: "LIM-2.B",
    cedEK: "LIM-2.B.1",
    prerequisites: ["sk-u1-continuity"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u1-continuity",
  },
  {
    id: "sk-u2-definition",
    title: "Derivative as a limit of average rates",
    description: "Write $f'(a)$ as a limit and interpret it with units.",
    unitId: "u2",
    cedTopic: "2.1–2.3",
    cedObjective: "CHA-2.A",
    cedEK: "CHA-2.A.1",
    prerequisites: ["sk-u1-limit-value", "sk-f-slope"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u2-derivative-limit",
  },
  {
    id: "sk-u2-differentiability",
    title: "Differentiability versus continuity",
    description: "Identify corners, cusps, and vertical tangents; continuity is necessary but not sufficient.",
    unitId: "u2",
    cedTopic: "2.4",
    cedObjective: "FUN-2.A",
    cedEK: "FUN-2.A.1",
    prerequisites: ["sk-u2-definition", "sk-u1-continuity"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u2-derivative-limit",
  },
  {
    id: "sk-u2-rules",
    title: "Elementary derivative rules",
    description: "Differentiate polynomials, exponentials, sine and cosine, products and quotients.",
    unitId: "u2",
    cedTopic: "2.5–2.9",
    cedObjective: "FUN-3.A",
    cedEK: "FUN-3.A.1",
    prerequisites: ["sk-u2-definition"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u2-elementary-rules",
  },
  {
    id: "sk-u3-chain",
    title: "Chain rule",
    description: "Differentiate compositions, including each inner factor, and name the inner function.",
    unitId: "u3",
    cedTopic: "3.1–3.2",
    cedObjective: "FUN-3.C",
    cedEK: "FUN-3.C.1",
    prerequisites: ["sk-u2-rules"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u3-chain",
  },
  {
    id: "sk-u3-implicit",
    title: "Implicit differentiation",
    description: "Differentiate relations in $x$ and $y$ and solve for $dy/dx$ at a point.",
    unitId: "u3",
    cedTopic: "3.2",
    cedObjective: "FUN-3.D",
    cedEK: "FUN-3.D.1",
    prerequisites: ["sk-u3-chain"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u3-implicit",
  },
  {
    id: "sk-u3-inverse",
    title: "Inverse function derivatives",
    description: "Use $(f^{-1})'(a)=1/f'(b)$ where $f(b)=a$, with a nonzero derivative check.",
    unitId: "u3",
    cedTopic: "3.3",
    cedObjective: "FUN-3.E",
    cedEK: "FUN-3.E.1",
    prerequisites: ["sk-u3-chain"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u3-implicit",
  },
  {
    id: "sk-u4-context",
    title: "Derivative in context with units",
    description: "Translate a verbal rate into a signed quantity and interpret $f'(t)$ in the situation.",
    unitId: "u4",
    cedTopic: "4.1–4.2",
    cedObjective: "CHA-3.A",
    cedEK: "CHA-3.A.1",
    prerequisites: ["sk-u2-definition"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u4-context",
  },
  {
    id: "sk-u4-related",
    title: "Related rates setup",
    description: "Write the relating equation first; substitute known values only after differentiating.",
    unitId: "u4",
    cedTopic: "4.4–4.5",
    cedObjective: "CHA-3.C",
    cedEK: "CHA-3.C.1",
    prerequisites: ["sk-u3-chain", "sk-u4-context"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u4-related-rates",
  },
  {
    id: "sk-u4-linear",
    title: "Local linear approximation",
    description: "Use the tangent line to estimate nearby values and discuss over/underestimate from concavity.",
    unitId: "u4",
    cedTopic: "4.6",
    cedObjective: "CHA-3.F",
    cedEK: "CHA-3.F.1",
    prerequisites: ["sk-u2-definition"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u4-context",
  },
  {
    id: "sk-u5-theorems",
    title: "MVT and Extreme Value Theorem conditions",
    description: "Check hypotheses before concluding a guaranteed $c$ or an extreme value on a closed interval.",
    unitId: "u5",
    cedTopic: "5.1",
    cedObjective: "FUN-1.B",
    cedEK: "FUN-1.B.1",
    prerequisites: ["sk-u1-continuity", "sk-u2-differentiability"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u5-extrema",
  },
  {
    id: "sk-u5-extrema",
    title: "Increasing, decreasing, and extrema from sign charts",
    description: "Use $f'$ sign changes, not merely $f'=0$, to classify extrema.",
    unitId: "u5",
    cedTopic: "5.2–5.5",
    cedObjective: "FUN-1.C",
    cedEK: "FUN-1.C.1",
    prerequisites: ["sk-u2-rules"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u5-extrema",
  },
  {
    id: "sk-u5-optimisation",
    title: "Closed-interval optimisation",
    description: "Candidates are critical points and endpoints; compare values, with units.",
    unitId: "u5",
    cedTopic: "5.10–5.11",
    cedObjective: "FUN-4.B",
    cedEK: "FUN-4.B.1",
    prerequisites: ["sk-u5-extrema"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u5-from-derivative",
  },
  {
    id: "sk-u6-accumulation",
    title: "Signed accumulation versus geometric area",
    description: "Interpret $\\int_a^b f$ as net change; area requests absolute values or splitting at zeros.",
    unitId: "u6",
    cedTopic: "6.1–6.3",
    cedObjective: "CHA-4.A",
    cedEK: "CHA-4.A.1",
    prerequisites: ["sk-f-slope"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u6-ftc",
  },
  {
    id: "sk-u6-ftc",
    title: "FTC and variable limits",
    description: "If $A(x)=\\int_a^x f$, then $A'(x)=f(x)$ when $f$ is continuous; chain rule for $x^2$ limits.",
    unitId: "u6",
    cedTopic: "6.4–6.8",
    cedObjective: "FUN-6.B",
    cedEK: "FUN-6.B.1",
    prerequisites: ["sk-u6-accumulation", "sk-u3-chain"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u6-ftc",
  },
  {
    id: "sk-u6-antiderivative",
    title: "Antiderivatives and substitution",
    description: "Undo elementary derivatives; substitution requires a matching inner derivative. Integration by parts and partial fractions are BC-optional and excluded from AB mastery.",
    unitId: "u6",
    cedTopic: "6.8–6.9",
    cedObjective: "FUN-6.C",
    cedEK: "FUN-6.C.1",
    prerequisites: ["sk-u2-rules", "sk-u3-chain"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u6-antiderivatives",
  },
  {
    id: "sk-u7-verify",
    title: "Verify a proposed DE solution",
    description: "Differentiate the candidate and substitute; check the initial condition separately.",
    unitId: "u7",
    cedTopic: "7.1–7.2",
    cedObjective: "FUN-7.A",
    cedEK: "FUN-7.A.1",
    prerequisites: ["sk-u2-rules"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u7-slope-fields",
  },
  {
    id: "sk-u7-slope",
    title: "Slope fields",
    description: "Match a slope field to $dy/dx=F(x,y)$ and justify a particular curve through a point.",
    unitId: "u7",
    cedTopic: "7.3",
    cedObjective: "FUN-7.C",
    cedEK: "FUN-7.C.1",
    prerequisites: ["sk-u7-verify"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u7-slope-fields",
  },
  {
    id: "sk-u7-separate",
    title: "Separable differential equations",
    description: "Separate variables, integrate, and apply $y(x_0)=y_0$. Logistic models are BC-optional.",
    unitId: "u7",
    cedTopic: "7.6–7.8",
    cedObjective: "FUN-7.D",
    cedEK: "FUN-7.D.1",
    prerequisites: ["sk-u6-antiderivative"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u7-separation",
  },
  {
    id: "sk-u8-average",
    title: "Average value and net change",
    description: "Average value is $\\frac{1}{b-a}\\int_a^b f$. Net change of $s$ is $\\int v$; total distance uses $|v|$.",
    unitId: "u8",
    cedTopic: "8.1–8.2",
    cedObjective: "CHA-4.D",
    cedEK: "CHA-4.D.1",
    prerequisites: ["sk-u6-accumulation"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u8-avg-net",
  },
  {
    id: "sk-u8-area",
    title: "Area between curves",
    description: "Choose $dx$ or $dy$, identify upper/lower or right/left, and check intersection bounds.",
    unitId: "u8",
    cedTopic: "8.4–8.6",
    cedObjective: "CHA-5.A",
    cedEK: "CHA-5.A.1",
    prerequisites: ["sk-u6-antiderivative"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u8-avg-net",
  },
  {
    id: "sk-u8-volume",
    title: "Volumes of known cross-section, disks, and washers",
    description: "Draw a representative slice, write $A(x)$ or $\\pi(R^2-r^2)$, and integrate. Arc length is BC-optional.",
    unitId: "u8",
    cedTopic: "8.7–8.12",
    cedObjective: "CHA-5.B",
    cedEK: "CHA-5.B.1",
    prerequisites: ["sk-u8-area"],
    abBcScope: "AB",
    evidencePolicy: P,
    remediationLessonId: "u8-volume",
  },
];

export const SKILL_BY_ID = Object.fromEntries(SKILLS.map((s) => [s.id, s]));
export const UNIT_BY_ID = Object.fromEntries(UNITS.map((u) => [u.id, u]));
